#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

SRC="/usr/local/src"
VERSION=2.1.11
TAG=FoswikiRelease02x01x11
FILE=Foswiki-$VERSION.tgz
SHA256=3a490eb460db4ca69d73dfe44c7984889552e5313eff60162760e80e66e5eba6
URL="https://github.com/foswiki/distro/releases/download/$TAG/$FILE"

dl $URL $SRC
echo "$SHA256  $SRC/$FILE" | sha256sum --check
