#!/bin/bash -ex

SRC=/usr/local/src
WEBROOT=/var/www/foswiki

# unpack foswiki, overlay foswiki configuration
tar -zxf $SRC/Foswiki-*.tgz -C $(dirname $WEBROOT)
rsync -a /var/www/Foswiki-*/ $WEBROOT
rm -r /var/www/Foswiki-*

CONFIG="perl -CA $WEBROOT/tools/configure -save" 
$CONFIG -noprompt # auto default config (writes config as root)
$CONFIG -set {EnableEmail}='1' \
        -set {Email}{MailMethod}='MailProgram' \
        -set {MailProgram}='/usr/sbin/sendmail -t -oi -oeq' \
        -set {SafeEnvPath}='/usr/local/bin:/usr/bin:/bin'

# ensure that configure.log is owned by www-data
touch $WEBROOT/working/logs/configure.log

chown -R www-data:www-data $WEBROOT

# apache configuration
a2dissite 000-default
a2enmod cgid
a2enmod rewrite
a2ensite foswiki
a2enmod access_compat

# cleanup
rm -rf $SRC/Foswiki*
rm -rf $SRC/foswiki*
# clean orig conf files
rm -f $WEBROOT/lib/LocalSite.cfg.*
