#!/bin/bash -e
# set foswiki admin password, email and domain

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF 
$INITHOOKS_PATH/bin/foswiki.py --pass="$APP_PASS" --email="$APP_EMAIL" --domain="$APP_DOMAIN"
chmod 600 /var/www/foswiki/data/.htpasswd
chown www-data:www-data /var/www/foswiki/data/.htpasswd
